import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1440px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["IBM Plex Sans", "ui-sans-serif", "sans-serif"],
        display: ["Manrope", "IBM Plex Sans", "ui-sans-serif", "sans-serif"],
        ui: ["IBM Plex Sans", "ui-sans-serif", "sans-serif"],
        sora: ["Manrope", "IBM Plex Sans", "ui-sans-serif", "sans-serif"],
      },
      fontSize: {
        display: ["6rem", { lineHeight: "0.95", fontWeight: "700" }],
        "display-mobile": ["3rem", { lineHeight: "0.98", fontWeight: "700" }],
        h1: ["4.5rem", { lineHeight: "1", fontWeight: "700" }],
        "h1-mobile": ["2.25rem", { lineHeight: "1.05", fontWeight: "700" }],
        h2: ["3rem", { lineHeight: "1.05", fontWeight: "700" }],
        "h2-mobile": ["1.875rem", { lineHeight: "1.1", fontWeight: "700" }],
        h3: ["1.25rem", { lineHeight: "1.2", fontWeight: "650" }],
        body: ["1rem", { lineHeight: "1.65", fontWeight: "400" }],
        ui: ["0.875rem", { lineHeight: "1.45", fontWeight: "500" }],
        label: ["0.75rem", { lineHeight: "1.35", fontWeight: "650" }],

        "hero-headline-desktop": ["6rem", { lineHeight: "0.95", fontWeight: "700" }],
        "hero-headline-mobile": ["3rem", { lineHeight: "0.98", fontWeight: "700" }],
        "section-headline-desktop": ["3rem", { lineHeight: "1.05", fontWeight: "700" }],
        "section-headline-mobile": ["1.875rem", { lineHeight: "1.1", fontWeight: "700" }],
        "subheadline-desktop": ["1.125rem", { lineHeight: "1.65", fontWeight: "400" }],
        "subheadline-mobile": ["1rem", { lineHeight: "1.65", fontWeight: "400" }],
        "body-desktop": ["1rem", { lineHeight: "1.65", fontWeight: "400" }],
        "body-mobile": ["0.9375rem", { lineHeight: "1.6", fontWeight: "400" }],
        "secondary-body-desktop": ["0.9375rem", { lineHeight: "1.55", fontWeight: "400" }],
        "secondary-body-mobile": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "small-text": ["0.8125rem", { lineHeight: "1.45", fontWeight: "500" }],
        "cta-text": ["0.875rem", { lineHeight: "1", fontWeight: "650" }],
        "cta-text-mobile": ["0.875rem", { lineHeight: "1", fontWeight: "650" }],
      },
      lineHeight: {
        "hero-headline": "0.95",
        "section-headline": "1.05",
        subheadline: "1.65",
        body: "1.65",
        "small-text": "1.45",
        "cta-text": "1",
      },
      letterSpacing: {
        tighter: "0em",
        tight: "0em",
        normal: "0em",
        wide: "0.04em",
        wider: "0.08em",
        widest: "0.12em",
        "hero-headline": "0em",
        "section-headline": "0em",
        subheadline: "0em",
        body: "0em",
        "small-text": "0.02em",
        "cta-text": "0em",
        uppercase: "0.08em",
      },
      maxWidth: {
        prose: "68ch",
        "container-lg": "1440px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: "hsl(var(--surface))",
        "surface-raised": "hsl(var(--surface-raised))",

        brand: {
          primary: "hsl(var(--primary))",
          secondary: "hsl(var(--accent))",
          ink: "hsl(var(--foreground))",
        },
        "text-primary": "hsl(var(--text-primary))",
        "text-secondary": "hsl(var(--text-secondary))",
        "text-muted": "hsl(var(--text-muted))",
        "text-disabled": "hsl(var(--text-disabled))",

        primary: {
          DEFAULT: "hsl(var(--primary))",
          hover: "hsl(var(--primary-hover))",
          foreground: "hsl(var(--primary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        error: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted-bg))",
          foreground: "hsl(var(--muted-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          bg: "hsl(var(--sidebar-bg))",
        },
        header: {
          bg: "hsl(var(--header-bg))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        status: {
          active: "hsl(var(--status-active))",
          inactive: "hsl(var(--status-inactive))",
          paused: "hsl(var(--status-paused))",
        },

        "premium-blue": "hsl(var(--primary))",
        "premium-blue-light": "hsl(var(--accent))",
        "premium-dark": "hsl(var(--background))",
        "premium-surface": "hsl(var(--card))",
        "premium-surface-secondary": "hsl(var(--surface))",
        "accent-orange": "hsl(var(--warning))",
        "accent-teal": "hsl(var(--accent))",
        "accent-purple": "hsl(var(--primary))",
        "accent-pink": "hsl(var(--destructive))",
        "accent-green": "hsl(var(--success))",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        card: "var(--shadow-card)",
        panel: "var(--shadow-panel)",
        lifted: "var(--shadow-panel)",
        "card-hover": "var(--shadow-panel)",
        sidebar: "var(--shadow-sidebar)",
        premium: "var(--shadow-focus)",
        "glow-sm": "var(--shadow-focus)",
        "glow-md": "var(--shadow-focus)",
        "glow-lg": "var(--shadow-focus)",
        "btn-primary": "var(--shadow-button)",
        "btn-primary-hover": "var(--shadow-button-hover)",
        dashboard: "var(--shadow-panel)",
      },
      backgroundImage: {
        "gradient-premium": "linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--accent)) 100%)",
        "gradient-orange": "linear-gradient(135deg, hsl(var(--warning)) 0%, hsl(var(--primary)) 100%)",
        "gradient-teal": "linear-gradient(135deg, hsl(var(--accent)) 0%, hsl(var(--success)) 100%)",
        "gradient-purple": "linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--accent)) 100%)",
        "gradient-green": "linear-gradient(135deg, hsl(var(--success)) 0%, hsl(var(--accent)) 100%)",
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      transitionDuration: {
        fast: "150ms",
        DEFAULT: "200ms",
        slow: "280ms",
      },
      transitionTimingFunction: {
        productive: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-accordion-content-height)", opacity: "1" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(8px)" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.98)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-out-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(100%)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        "accordion-up": "accordion-up 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        "fade-in": "fade-in 280ms cubic-bezier(0.22, 1, 0.36, 1)",
        "fade-out": "fade-out 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        "scale-in": "scale-in 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        "slide-in-right": "slide-in-right 240ms cubic-bezier(0.22, 1, 0.36, 1)",
        "slide-out-right": "slide-out-right 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
