export const FIELD_LABELS: Record<string, string> = {
  q1_business_name: 'Business name',
  q2_website_or_socials: 'Website or social profile',
  q2_website: 'Website',
  q2_social_links: 'Social profiles',
  q4_languages: 'Language',
  q3_market_scope: 'Market scope',
  q3_geo: 'Country and city',
  q3_country: 'Country',
  q3_city: 'City',
  industry_niche: 'Industry / niche',
  primary_goal: 'Primary goal',
  conversion_path: 'Conversion path',
  conversion_link_required: 'Conversion link',
  offers: 'Top offers',
  audience_type: 'Audience type',
  primary_customer: 'Primary customer',
  main_objection: 'Main objection',
  q9_pain_points: 'Pain points',
  brand_voice: 'Brand voice',
  content_style: 'Content style',
  on_camera_availability: 'On-camera availability',
  available_assets: 'Available assets',
  proof_types: 'Proof types',
  competitor_link: 'Competitor link',
  platforms: 'Platforms',
  formats: 'Content formats',
  cadence_requirement: 'Cadence',
  response_handling: 'Response handling',
  q13_differentiators: 'Differentiators',
};

export function getFieldLabel(fieldKey: string): string {
  return FIELD_LABELS[fieldKey] ?? fieldKey.replace(/_/g, ' ');
}
