import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <Link to="/" className="text-sm text-text-muted hover:text-foreground transition-colors">
          ← Back to home
        </Link>

        <h1 className="mt-6 text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-text-muted">Last updated: February 2, 2026</p>

        <div className="mt-10 space-y-6 text-text-secondary leading-relaxed">
          <p>
            These Terms of Service govern your access to and use of SMMAHUB. By using the service, you agree to these
            terms.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-foreground">Use of the Service</h2>
            <p className="mt-2">
              You agree to use the service responsibly and in compliance with applicable laws. You are responsible for
              maintaining the confidentiality of your account credentials.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">Your Data</h2>
            <p className="mt-2">
              You retain ownership of your content and data. You are responsible for the accuracy and legality of the
              information you provide.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">Disclaimer</h2>
            <p className="mt-2">
              The service is provided “as is” without warranties of any kind. Outputs generated by AI should be reviewed
              before use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">Contact</h2>
            <p className="mt-2">
              Questions? Email{" "}
              <a className="text-brand-primary hover:underline" href="mailto:contact@smmahub.com">
                contact@smmahub.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}

