export enum TaskType {
  CHAT_GENERAL = "CHAT_GENERAL",
  CHAT_ADMIN_ONBOARDING = "CHAT_ADMIN_ONBOARDING",
  AGENCY_ADMIN_SETUP_GUIDED_V2 = "AGENCY_ADMIN_SETUP_GUIDED_V2",
  AGENCY_ADMIN_GENERAL_CHAT = "AGENCY_ADMIN_GENERAL_CHAT",
  AGENCY_ADMIN_SETUP_EXTRACT = "AGENCY_ADMIN_SETUP_EXTRACT",
  CLIENT_PORTAL_QA = "CLIENT_PORTAL_QA",
  SUMMARIZE = "SUMMARIZE",
  EXTRACT_STRUCTURED = "EXTRACT_STRUCTURED",
  CLASSIFY_INTENT = "CLASSIFY_INTENT",
  STRATEGY_PLAN = "STRATEGY_PLAN",
  CONTENT_IDEAS = "CONTENT_IDEAS",
  SCRIPT_WRITING = "SCRIPT_WRITING",
  TOOL_EXECUTION = "TOOL_EXECUTION",
  EMBED_TEXT = "EMBED_TEXT",
}

export type TaskTypeKey = `${TaskType}`;
