export enum ToolType {
  CREATE_CLIENT = "create_client",
  DRAFT_OFFER = "draft_offer",
  UPDATE_BRAIN = "update_brain",
  SCHEDULE_TASK = "schedule_task",
  CREATE_PROJECT = "create_project",
  UPDATE_PROJECT_STATUS = "update_project_status",
  ASSIGN_PROJECT_ASSET = "assign_project_asset",
  SCHEDULE_POST = "schedule_post",
  UPDATE_TASK_STATUS = "update_task_status",
  UPDATE_TASK_PRIORITY = "update_task_priority",
  REQUEST_APPROVAL = "request_approval",
  SEND_MESSAGE = "send_message",
  SEARCH_KNOWLEDGE_BASE = "search_knowledge_base",
  GET_CLIENT_HISTORY = "get_client_history",
  FETCH_CAMPAIGN_PERFORMANCE = "fetch_campaign_performance",
  GET_ACCOUNT_DETAILS = "get_account_details",
  UPDATE_CLIENT_RECORD = "update_client_record",
  CREATE_NEW_TASK = "create_new_task",
  GENERATE_STRATEGY_REPORT = "generate_strategy_report",
  TRIGGER_EMAIL_SEQUENCE = "trigger_email_sequence",
  PROPOSE_MEMORY_WRITE = "propose_memory_write",
  VALIDATE_PII = "validate_pii",
  CHECK_COMPLIANCE_FLAGS = "check_compliance_flags",
  APPROVE_ACTION = "approve_action",
}

export type ToolSchema = {
  type: ToolType;
  description: string;
  parameters: Record<string, { type: string; description: string; required: boolean }>;
  returns?: string;
  scope: "tenant-read" | "tenant-write" | "global-admin";
  budget: { maxCalls: number; maxSeconds: number };
  timeoutMs: number;
  retries: number;
};

export const TOOL_REGISTRY: Record<ToolType, ToolSchema> = {
  [ToolType.CREATE_CLIENT]: {
    type: ToolType.CREATE_CLIENT,
    description: "Create a new client record in the CRM",
    parameters: {
      name: { type: "string", description: "Client company name", required: true },
      website: { type: "string", description: "Client website URL", required: false },
      niche: { type: "string", description: "Client industry/niche", required: false },
    },
    returns: "client_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.DRAFT_OFFER]: {
    type: ToolType.DRAFT_OFFER,
    description: "Generate a service offer draft",
    parameters: {
      service_type: { type: "string", description: "Type of service", required: true },
      pricing_range: { type: "string", description: "Price range", required: false },
    },
    returns: "offer_text",
    scope: "tenant-read",
    budget: { maxCalls: 2, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 0,
  },
  [ToolType.UPDATE_BRAIN]: {
    type: ToolType.UPDATE_BRAIN,
    description: "Update a field in the agency brain",
    parameters: {
      field: { type: "string", description: "Dot path to update (e.g., setup_profile_v1.agency.niche)", required: true },
      value: { type: "string", description: "New value to store", required: true },
    },
    returns: "brain_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.SCHEDULE_TASK]: {
    type: ToolType.SCHEDULE_TASK,
    description: "Create a task reminder",
    parameters: {
      title: { type: "string", description: "Task title", required: true },
      due_date: { type: "string", description: "Due date (ISO 8601)", required: true },
      notes: { type: "string", description: "Additional notes", required: false },
      client_id: { type: "string", description: "Client ID (defaults to most recent if omitted)", required: false },
    },
    returns: "task_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.CREATE_PROJECT]: {
    type: ToolType.CREATE_PROJECT,
    description: "Create a new content project for a client",
    parameters: {
      title: { type: "string", description: "Project title", required: true },
      client_id: { type: "string", description: "Client ID (UUID)", required: true },
      description: { type: "string", description: "Project description", required: false },
      platforms: { type: "string", description: "Comma-separated platforms (instagram,facebook,linkedin,tiktok,youtube)", required: false },
    },
    returns: "project_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.UPDATE_PROJECT_STATUS]: {
    type: ToolType.UPDATE_PROJECT_STATUS,
    description: "Update project pipeline status",
    parameters: {
      project_id: { type: "string", description: "Project ID (UUID)", required: true },
      status: { type: "string", description: "New status (idea|scripting|production|internal_review|client_review|approved|scheduled|published)", required: true },
    },
    returns: "project_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.ASSIGN_PROJECT_ASSET]: {
    type: ToolType.ASSIGN_PROJECT_ASSET,
    description: "Link an asset to a project",
    parameters: {
      project_id: { type: "string", description: "Project ID (UUID)", required: true },
      asset_id: { type: "string", description: "Asset ID (UUID)", required: true },
      is_final_content: { type: "string", description: "Mark as final content (true/false)", required: false },
    },
    returns: "project_asset_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.SCHEDULE_POST]: {
    type: ToolType.SCHEDULE_POST,
    description: "Schedule a project for publishing to a platform",
    parameters: {
      project_id: { type: "string", description: "Project ID (UUID)", required: true },
      platform: { type: "string", description: "Platform (instagram|facebook|linkedin|tiktok|youtube)", required: true },
      scheduled_for: { type: "string", description: "Scheduled datetime (ISO 8601)", required: true },
      caption: { type: "string", description: "Post caption", required: false },
      hashtags: { type: "string", description: "Hashtags (space-separated)", required: false },
    },
    returns: "scheduled_post_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 4 },
    timeoutMs: 4000,
    retries: 1,
  },
  [ToolType.UPDATE_TASK_STATUS]: {
    type: ToolType.UPDATE_TASK_STATUS,
    description: "Update task status",
    parameters: {
      task_id: { type: "string", description: "Task ID (UUID)", required: true },
      status: { type: "string", description: "New status (todo|in_progress|completed|cancelled)", required: true },
    },
    returns: "task_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.UPDATE_TASK_PRIORITY]: {
    type: ToolType.UPDATE_TASK_PRIORITY,
    description: "Update task priority level",
    parameters: {
      task_id: { type: "string", description: "Task ID (UUID)", required: true },
      priority: { type: "string", description: "Priority (low|medium|high|urgent)", required: true },
    },
    returns: "task_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.REQUEST_APPROVAL]: {
    type: ToolType.REQUEST_APPROVAL,
    description: "Create an approval request for an asset version",
    parameters: {
      asset_version_id: { type: "string", description: "Asset version ID (UUID)", required: true },
      approver_id: { type: "string", description: "User ID of approver (UUID)", required: true },
      comments: { type: "string", description: "Optional comment", required: false },
    },
    returns: "approval_task_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 0,
  },
  [ToolType.SEND_MESSAGE]: {
    type: ToolType.SEND_MESSAGE,
    description: "Send a message in a conversation",
    parameters: {
      conversation_id: { type: "string", description: "Conversation ID (UUID)", required: true },
      body: { type: "string", description: "Message body", required: true },
      related_project_id: { type: "string", description: "Related project ID (UUID)", required: false },
    },
    returns: "message_id",
    scope: "tenant-write",
    budget: { maxCalls: 2, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 1,
  },
  [ToolType.SEARCH_KNOWLEDGE_BASE]: {
    type: ToolType.SEARCH_KNOWLEDGE_BASE,
    description: "Semantic search over internal knowledge base",
    parameters: {
      query: { type: "string", description: "Search query", required: true },
      tenant_id: { type: "string", description: "Agency ID", required: true },
      client_id: { type: "string", description: "Client ID (optional)", required: false },
      doc_types: { type: "string", description: "Comma-separated doc types", required: false },
      top_k: { type: "string", description: "Top K results", required: false },
    },
    returns: "matches",
    scope: "tenant-read",
    budget: { maxCalls: 3, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 2,
  },
  [ToolType.GET_CLIENT_HISTORY]: {
    type: ToolType.GET_CLIENT_HISTORY,
    description: "Summarize client history",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      limit: { type: "string", description: "Max items", required: false },
    },
    returns: "summary",
    scope: "tenant-read",
    budget: { maxCalls: 1, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 1,
  },
  [ToolType.FETCH_CAMPAIGN_PERFORMANCE]: {
    type: ToolType.FETCH_CAMPAIGN_PERFORMANCE,
    description: "Read campaign performance metrics",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      campaign_id: { type: "string", description: "Campaign ID", required: false },
      date_range: { type: "string", description: "Date range (YYYY-MM-DD..YYYY-MM-DD)", required: false },
    },
    returns: "metrics",
    scope: "tenant-read",
    budget: { maxCalls: 2, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 2,
  },
  [ToolType.GET_ACCOUNT_DETAILS]: {
    type: ToolType.GET_ACCOUNT_DETAILS,
    description: "Fetch non-sensitive account details",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
    },
    returns: "account_name",
    scope: "tenant-read",
    budget: { maxCalls: 1, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 1,
  },
  [ToolType.UPDATE_CLIENT_RECORD]: {
    type: ToolType.UPDATE_CLIENT_RECORD,
    description: "Update client record fields",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      fields: { type: "string", description: "JSON string of fields", required: true },
    },
    returns: "updated",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.CREATE_NEW_TASK]: {
    type: ToolType.CREATE_NEW_TASK,
    description: "Create a new task and assign to user",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      title: { type: "string", description: "Task title", required: true },
      due_date: { type: "string", description: "Due date (ISO 8601)", required: false },
      notes: { type: "string", description: "Notes", required: false },
    },
    returns: "task_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.GENERATE_STRATEGY_REPORT]: {
    type: ToolType.GENERATE_STRATEGY_REPORT,
    description: "Kick off strategy generation job",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      goal: { type: "string", description: "Goal", required: false },
    },
    returns: "job_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 5 },
    timeoutMs: 5000,
    retries: 1,
  },
  [ToolType.TRIGGER_EMAIL_SEQUENCE]: {
    type: ToolType.TRIGGER_EMAIL_SEQUENCE,
    description: "Start email sequence for client",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      sequence_id: { type: "string", description: "Sequence ID", required: true },
    },
    returns: "job_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 4 },
    timeoutMs: 4000,
    retries: 1,
  },
  [ToolType.PROPOSE_MEMORY_WRITE]: {
    type: ToolType.PROPOSE_MEMORY_WRITE,
    description: "Propose long-term memory write",
    parameters: {
      tenant_id: { type: "string", description: "Agency ID", required: true },
      scope: { type: "string", description: "Scope", required: false },
      fact: { type: "string", description: "Fact", required: true },
      requires_approval: { type: "string", description: "Requires approval (true/false)", required: false },
    },
    returns: "proposal_id",
    scope: "tenant-write",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 1,
  },
  [ToolType.VALIDATE_PII]: {
    type: ToolType.VALIDATE_PII,
    description: "Detect PII in text",
    parameters: {
      text: { type: "string", description: "Text to scan", required: true },
    },
    returns: "has_pii",
    scope: "tenant-read",
    budget: { maxCalls: 2, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 1,
  },
  [ToolType.CHECK_COMPLIANCE_FLAGS]: {
    type: ToolType.CHECK_COMPLIANCE_FLAGS,
    description: "Validate action against compliance rules",
    parameters: {
      client_id: { type: "string", description: "Client ID", required: true },
      action: { type: "string", description: "Proposed action", required: true },
    },
    returns: "allowed",
    scope: "tenant-read",
    budget: { maxCalls: 1, maxSeconds: 2 },
    timeoutMs: 2000,
    retries: 1,
  },
  [ToolType.APPROVE_ACTION]: {
    type: ToolType.APPROVE_ACTION,
    description: "Human approval gate",
    parameters: {
      proposal_id: { type: "string", description: "Approval task ID", required: true },
      approver_id: { type: "string", description: "Approver ID", required: true },
      decision: { type: "string", description: "approved|changes_requested", required: true },
    },
    returns: "status",
    scope: "global-admin",
    budget: { maxCalls: 1, maxSeconds: 3 },
    timeoutMs: 3000,
    retries: 0,
  },
};
